### ISSUE TITLE
Funcionalidad a hacer

### ISSUE THREAD

**Issue by PascualDaniel** [Nazsgull/FPS_Godot#2]
[ ] Inventario de objetos ••
[ ] Menú opciones ••
[ ] Sonidos al caminar •
[ ] Unir todos los menús
[ ] Permitir bloqueo de estados de movimiento del jugador desde el editor••
[ ] Sonido puerta simple
[ ] Sonido puerta complicada 
[ ] Sonido pulsación botónes?
[ ] Keypad
[ ] Pantalla de carga
[ ] Pulido final (icono, splash, pantalla completa, nombre, antialiasing etc)
[ ] Icono
[ ] Splash
[ ] Pantalla completa
[ ] Nombre de aplicación
[ ] Antialiasing
[ ] Fundido desde negro al iniciar el juego
[ ] Confirmación de salida a menú principal 
[ ] Desacoplar objetos (usar señales) *
[ ] Créditos
[ ] Documentación 

Shader para el clippeo arma

**Comment by Nazsgull** [comment]
Lo he fragmentado en issues individuales.
